'use strict';
const $ = s => document.querySelector(s);
const abbr = {Alabama:'AL',Alaska:'AK',Arizona:'AZ',Arkansas:'AR',California:'CA',Colorado:'CO',Connecticut:'CT',Delaware:'DE',Florida:'FL',Georgia:'GA',Hawaii:'HI',Idaho:'ID',Illinois:'IL',Indiana:'IN',Iowa:'IA',Kansas:'KS',Kentucky:'KY',Louisiana:'LA',Maine:'ME',Maryland:'MD',Massachusetts:'MA',Michigan:'MI',Minnesota:'MN',Mississippi:'MS',Missouri:'MO',Montana:'MT',Nebraska:'NE',Nevada:'NV','New Hampshire':'NH','New Jersey':'NJ','New Mexico':'NM','New York':'NY','North Carolina':'NC','North Dakota':'ND',Ohio:'OH',Oklahoma:'OK',Oregon:'OR',Pennsylvania:'PA','Rhode Island':'RI','South Carolina':'SC','South Dakota':'SD',Tennessee:'TN',Texas:'TX',Utah:'UT',Vermont:'VT',Virginia:'VA',Washington:'WA','West Virginia':'WV',Wisconsin:'WI',Wyoming:'WY'};
const regions = {Northeast:['CT','ME','MA','NH','RI','VT','NJ','NY','PA'],Midwest:['IL','IN','MI','OH','WI','IA','KS','MN','MO','NE','ND','SD'],South:['DE','FL','GA','MD','NC','SC','VA','WV','AL','KY','MS','TN','AR','LA','OK','TX'],West:['AZ','CO','ID','MT','NV','NM','UT','WY','AK','CA','HI','OR','WA']};
const themes = [{name:'Forest',color:'#3e795b',bg:'#f1f3eb',empty:'#d9ded3',label:'#35483c'},{name:'Ocean',color:'#377a94',bg:'#edf4f5',empty:'#d5e3e7',label:'#294852'},{name:'Sunset',color:'#c36b43',bg:'#faf0e7',empty:'#eadccf',label:'#644836'},{name:'Midnight',color:'#8194db',bg:'#20283d',empty:'#3c4866',label:'#e4e7f0'},{name:'Berry',color:'#a55475',bg:'#f7edf2',empty:'#e7d7df',label:'#64394b'}];
let saved = {};
try { saved = JSON.parse(localStorage.getItem('fiftystates-v1') || '{}') || {}; } catch {}
const selected = new Set(Array.isArray(saved.visited) ? saved.visited.filter(s => Object.values(abbr).includes(s)) : []);
let themeIndex = Number.isInteger(saved.theme) && themes[saved.theme] ? saved.theme : 0;
let states = [], toastTimer;
$('#traveler').value = typeof saved.name === 'string' ? saved.name.slice(0,60) : '';
$('#show-labels').checked = saved.labels !== false;
function notify(message) { $('#status').textContent=message; clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('#status').textContent='',4000); }
function persist() { try {localStorage.setItem('fiftystates-v1',JSON.stringify({visited:[...selected],theme:themeIndex,name:$('#traveler').value,labels:$('#show-labels').checked}));} catch {notify('Browser saving is unavailable. You can still download your map.');} }
function refresh() {
  const count=selected.size;
  $('#total').textContent=count; $('#count').textContent=`${count} / 50`; $('#progress-fill').style.width=`${count*2}%`;
  $('.progress').setAttribute('aria-valuenow',count);
  $('#percentage').textContent=count===0?'Your adventure starts here.':count===50?'Fifty states. Countless memories.':`${count*2}% explored. So much more to discover.`;
  document.querySelectorAll('.state-path').forEach(p=>{const yes=selected.has(p.dataset.code);p.classList.toggle('visited',yes);p.setAttribute('aria-pressed',String(yes));p.setAttribute('aria-label',`${p.dataset.name}, ${yes?'visited':'not visited'}`);});
  document.querySelectorAll('.state-label').forEach(p=>p.classList.toggle('visited',selected.has(p.dataset.code)));
  document.querySelectorAll('.state-option input').forEach(c=>c.checked=selected.has(c.value));
  $('#state-labels').style.display=$('#show-labels').checked?'':'none';
  renderExplore();
}
function toggle(code){selected.has(code)?selected.delete(code):selected.add(code);refresh();persist();}
function applyTheme(index){themeIndex=index;const t=themes[index];const root=document.documentElement.style;root.setProperty('--selected',t.color);root.setProperty('--map-bg',t.bg);root.setProperty('--unvisited',t.empty);root.setProperty('--label',t.label);document.querySelectorAll('.theme').forEach((b,i)=>b.setAttribute('aria-checked',String(i===index)));persist();}
themes.forEach((t,i)=>{const b=document.createElement('button');b.className='theme';b.style.background=t.color;b.setAttribute('role','radio');b.setAttribute('aria-label',`${t.name} theme`);b.title=t.name;b.onclick=()=>applyTheme(i);$('#themes').append(b);});
$('#themes').setAttribute('role','radiogroup');$('#themes').setAttribute('aria-label','Map color theme');
$('#themes').onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const next=(themeIndex+(['ArrowRight','ArrowDown'].includes(e.key)?1:-1)+themes.length)%themes.length;applyTheme(next);$('#themes').children[next].focus();};
applyTheme(themeIndex);
function renderList(){const query=$('#search').value.trim().toLowerCase();$('#state-list').replaceChildren();let found=0;Object.entries(regions).forEach(([region,codes])=>{const matching=states.filter(s=>codes.includes(s.code)&&(s.properties.name.toLowerCase().includes(query)||s.code.toLowerCase().includes(query)));if(!matching.length)return;found+=matching.length;const group=document.createElement('div');group.className='state-group';const heading=document.createElement('h3');heading.textContent=region;group.append(heading);matching.forEach(s=>{const label=document.createElement('label');label.className='state-option';const input=document.createElement('input');input.type='checkbox';input.value=s.code;input.checked=selected.has(s.code);input.onchange=()=>toggle(s.code);label.append(input,document.createTextNode(s.properties.name));group.append(label);});$('#state-list').append(group);});if(!found){const p=document.createElement('p');p.textContent='No states found. Try a name or abbreviation.';$('#state-list').append(p);}}
$('#search').oninput=renderList;
$('#select-all').onclick=()=>{Object.values(abbr).forEach(s=>selected.add(s));refresh();persist();};
$('#clear').onclick=()=>{selected.clear();refresh();persist();};
$('#show-labels').onchange=()=>{refresh();persist();};$('#traveler').oninput=persist;
function route(){const explore=location.hash==='#explore';$('#map-view').hidden=explore;$('#explore-view').hidden=!explore;document.querySelectorAll('nav a').forEach(a=>{const active=a.hash===(explore?'#explore':'#map');a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.title=explore?'Explore — FiftyStates':'FiftyStates — Your American travel map';}
window.addEventListener('hashchange',route);route();
function renderExplore(){if(!states.length)return;const state=states.find(s=>s.code===$('#explore-state').value)||states[0];const region=Object.keys(regions).find(r=>regions[r].includes(state.code));$('#explore-info').replaceChildren();const h=document.createElement('h2');h.textContent=state.properties.name;const p=document.createElement('p');p.textContent=`${region} · ${selected.has(state.code)?'A part of your story.':'Still on the horizon.'}`;const b=document.createElement('button');b.textContent=selected.has(state.code)?'Remove from visited':'Mark as visited';b.onclick=()=>toggle(state.code);$('#explore-info').append(h,p,b);$('#parks-link').href=`https://www.nps.gov/state/${state.code.toLowerCase()}/index.htm`;$('#parks-link').textContent=`Explore parks in ${state.properties.name}`;}
$('#explore-state').onchange=renderExplore;
$('#about').onclick=()=>$('#credits').showModal();$('#close-credits').onclick=()=>$('#credits').close();
async function loadMap(){try{const response=await fetch('assets/states.json');if(!response.ok)throw Error('Map data unavailable');const data=await response.json();states=topojson.feature(data,data.objects.states).features.filter(s=>abbr[s.properties.name]).map(s=>({...s,code:abbr[s.properties.name]})).sort((a,b)=>a.properties.name.localeCompare(b.properties.name));if(states.length!==50)throw Error('Incomplete map data');const path=d3.geoPath();const g=d3.select('#state-paths');g.selectAll('path').data(states).join('path').attr('d',path).attr('class','state-path').attr('data-code',s=>s.code).attr('data-name',s=>s.properties.name).attr('tabindex',0).attr('role','button').on('click',(_,s)=>toggle(s.code)).on('keydown',(e,s)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle(s.code);}}).on('mouseenter',(_,s)=>$('#hover-state').textContent=s.properties.name).on('focus',(_,s)=>$('#hover-state').textContent=s.properties.name).on('mouseleave',()=>$('#hover-state').textContent='Click a state to mark it visited');const small=new Set(['RI','DE','DC','NJ','MA','CT']);d3.select('#state-labels').selectAll('text').data(states.filter(s=>!small.has(s.code))).join('text').attr('class','state-label').attr('data-code',s=>s.code).attr('text-anchor','middle').attr('dominant-baseline','middle').attr('transform',s=>`translate(${path.centroid(s)})`).text(s=>s.code);renderList();states.forEach(s=>{const o=document.createElement('option');o.value=s.code;o.textContent=s.properties.name;$('#explore-state').append(o);});$('#explore-state').value='WY';refresh();}catch(e){$('#state-list').textContent='The map couldn’t load. Please refresh to try again.';notify('The map couldn’t load. Please refresh to try again.');document.querySelectorAll('[data-format]').forEach(b=>b.disabled=true);console.error(e);}}
async function download(format){if(states.length!==50)return;const buttons=[...document.querySelectorAll('[data-format]')];buttons.forEach(b=>b.disabled=true);try{const t=themes[themeIndex];const source=$('#map-svg').cloneNode(true);source.setAttribute('xmlns','http://www.w3.org/2000/svg');source.setAttribute('viewBox','0 -110 975 820');source.setAttribute('width','1950');source.setAttribute('height','1640');source.removeAttribute('role');source.removeAttribute('aria-label');const ns='http://www.w3.org/2000/svg';const rect=document.createElementNS(ns,'rect');rect.setAttribute('x','0');rect.setAttribute('y','-110');rect.setAttribute('width','975');rect.setAttribute('height','820');rect.setAttribute('fill',t.bg);source.insertBefore(rect,source.firstChild);function text(value,x,y,size,color){const el=document.createElementNS(ns,'text');el.setAttribute('x',x);el.setAttribute('y',y);el.setAttribute('font-family','Arial, sans-serif');el.setAttribute('font-size',size);el.setAttribute('fill',color);el.textContent=value;source.append(el);}const name=$('#traveler').value.trim();text(name?`${name}’s American journey`:'My American journey',35,-58,30,t.label);text(`${selected.size} of 50 states explored · ${selected.size*2}%`,35,-20,18,t.label);text('FiftyStates · Every state has a story.',35,685,17,t.label);source.querySelectorAll('.state-path').forEach(p=>{p.setAttribute('fill',p.classList.contains('visited')?t.color:t.empty);p.setAttribute('stroke',t.bg);p.setAttribute('stroke-width','1.5');p.removeAttribute('class');p.removeAttribute('tabindex');});source.querySelectorAll('.state-label').forEach(p=>{p.setAttribute('fill',p.classList.contains('visited')?'#fff':t.label);p.setAttribute('font-family','Arial, sans-serif');p.setAttribute('font-size','13');p.removeAttribute('class');});const blob=new Blob([new XMLSerializer().serializeToString(source)],{type:'image/svg+xml;charset=utf-8'});const url=URL.createObjectURL(blob);let canvas;try{const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=url;});canvas=document.createElement('canvas');canvas.width=1950;canvas.height=1640;canvas.getContext('2d').drawImage(img,0,0);}finally{URL.revokeObjectURL(url);}if(format==='pdf'){const pdf=new jspdf.jsPDF({orientation:'landscape',unit:'mm',format:'a4'});pdf.addImage(canvas.toDataURL('image/png'),'PNG',8,10,281,189);pdf.save('fiftystates-map.pdf');}else{const data=await new Promise(resolve=>canvas.toBlob(resolve,format==='jpg'?'image/jpeg':'image/png',.95));if(!data)throw Error('Export failed');const out=URL.createObjectURL(data);const a=document.createElement('a');a.href=out;a.download=`fiftystates-map.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(out),1000);}notify('Your travel map is ready.');}catch(e){notify('Couldn’t export your map. Please try again.');console.error(e);}finally{buttons.forEach(b=>b.disabled=false);}}
document.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>download(b.dataset.format));
loadMap();
